"""Birth-time UTC offsets from the historical IANA rules.

Expected values were NOT taken from the code under test or from memory: they were
generated by an independent implementation (Node/ICU, tz database 2026b) that
searches for every UTC instant whose wall clock in the zone equals the local time.
The Tbilisi 1999-05-07 case is the one that exposed the original bug: the offset
was UTC+5 (daylight saving in force), not the +4 a person would reasonably type.
"""

from datetime import date, time

import pytest
import swisseph as swe
from fastapi.testclient import TestClient

from app.calc.astrology import build_natal_chart
from app.calc.ephemeris import to_julian_day
from app.calc.models import BirthData
from app.calc.timezone import resolve_birth_timezone
from app.main import app

TBILISI = (41.6934591, 44.8014495)
NEW_YORK = (40.7128, -74.0060)
SYDNEY = (-33.8688, 151.2093)
SAO_PAULO = (-23.5505, -46.6333)
SANTIAGO = (-33.4489, -70.6693)
TOKYO = (35.6762, 139.6503)
PHOENIX = (33.4484, -112.0740)
MUMBAI = (19.0760, 72.8777)
KATHMANDU = (27.7172, 85.3240)
REYKJAVIK = (64.1466, -21.9426)
APIA = (-13.8333, -171.7667)

# (id, coords, local date, local time, zone, status, expected offsets (hours), is_dst of first)
OK_CASES = [
    ("tbilisi-1999-05-07-dst", TBILISI, date(1999, 5, 7), time(23, 30), "Asia/Tbilisi", [5.0], True),
    ("tbilisi-1999-winter", TBILISI, date(1999, 12, 15), time(12, 0), "Asia/Tbilisi", [4.0], False),
    ("tbilisi-2024-dst-abolished", TBILISI, date(2024, 7, 1), time(12, 0), "Asia/Tbilisi", [4.0], False),
    ("tbilisi-1870-local-mean-time", TBILISI, date(1870, 6, 1), time(12, 0), "Asia/Tbilisi", [2.983333], False),
    ("nyc-2023-us-dst", NEW_YORK, date(2023, 7, 4), time(12, 0), "America/New_York", [-4.0], True),
    ("nyc-2023-us-standard", NEW_YORK, date(2023, 1, 15), time(12, 0), "America/New_York", [-5.0], False),
    ("nyc-1999-before-fall-back", NEW_YORK, date(1999, 10, 30), time(12, 0), "America/New_York", [-4.0], True),
    ("nyc-1999-after-fall-back", NEW_YORK, date(1999, 11, 1), time(12, 0), "America/New_York", [-5.0], False),
    ("nyc-2006-old-us-rule", NEW_YORK, date(2006, 3, 30), time(12, 0), "America/New_York", [-5.0], False),
    ("nyc-2007-new-us-rule", NEW_YORK, date(2007, 3, 30), time(12, 0), "America/New_York", [-4.0], True),
    ("sydney-2023-southern-summer-dst", SYDNEY, date(2023, 1, 15), time(12, 0), "Australia/Sydney", [11.0], True),
    ("sydney-2023-southern-winter", SYDNEY, date(2023, 7, 15), time(12, 0), "Australia/Sydney", [10.0], False),
    ("sydney-2000-olympic-early-dst", SYDNEY, date(2000, 9, 20), time(12, 0), "Australia/Sydney", [11.0], True),
    ("sao-paulo-2015-dst", SAO_PAULO, date(2015, 12, 15), time(12, 0), "America/Sao_Paulo", [-2.0], True),
    ("sao-paulo-2019-dst-abolished", SAO_PAULO, date(2019, 12, 15), time(12, 0), "America/Sao_Paulo", [-3.0], False),
    ("santiago-2024-summer-dst", SANTIAGO, date(2024, 1, 15), time(12, 0), "America/Santiago", [-3.0], True),
    ("santiago-2024-winter", SANTIAGO, date(2024, 7, 15), time(12, 0), "America/Santiago", [-4.0], False),
    ("tokyo-no-dst", TOKYO, date(2000, 7, 1), time(12, 0), "Asia/Tokyo", [9.0], False),
    ("phoenix-us-no-dst", PHOENIX, date(2023, 7, 1), time(12, 0), "America/Phoenix", [-7.0], False),
    ("mumbai-half-hour", MUMBAI, date(1999, 5, 7), time(12, 0), "Asia/Kolkata", [5.5], False),
    ("kathmandu-quarter-hour", KATHMANDU, date(2000, 1, 1), time(12, 0), "Asia/Kathmandu", [5.75], False),
    ("reykjavik-utc-no-dst", REYKJAVIK, date(2023, 7, 1), time(12, 0), "Atlantic/Reykjavik", [0.0], False),
]


@pytest.mark.parametrize("case", OK_CASES, ids=[c[0] for c in OK_CASES])
def test_offset_matches_independent_historical_reference(case):
    _id, (lat, lon), d, t, zone, offsets, is_dst = case
    r = resolve_birth_timezone(lat, lon, d, t)
    assert r.status == "ok"
    assert r.tz_name == zone
    assert r.utc_offset_hours == pytest.approx(offsets[0], abs=1e-6)
    assert r.offsets[0].is_dst is is_dst
    assert r.time_assumed is False


def test_george_stage0_case_is_utc_plus_5_not_the_plus_4_a_person_would_type():
    r = resolve_birth_timezone(*TBILISI, date(1999, 5, 7), time(23, 30))
    assert r.utc_offset_hours == 5.0
    assert r.utc_offset_hours not in (0.0, 4.0)


def test_repeated_clock_time_is_ambiguous_with_both_offsets_never_guessed():
    r = resolve_birth_timezone(*NEW_YORK, date(2023, 11, 5), time(1, 30))
    assert r.status == "ambiguous"
    assert r.utc_offset_hours is None
    assert [o.utc_offset_hours for o in r.offsets] == [-4.0, -5.0]  # daylight reading first
    assert [o.is_dst for o in r.offsets] == [True, False]


@pytest.mark.parametrize(
    "coords,d,t",
    [
        (NEW_YORK, date(2023, 3, 12), time(2, 30)),  # clocks skipped 02:00 -> 03:00
        (APIA, date(2011, 12, 30), time(12, 0)),  # Samoa skipped this calendar day entirely
    ],
    ids=["clock-skipped-hour", "calendar-day-never-happened"],
)
def test_skipped_local_time_is_nonexistent_not_silently_shifted(coords, d, t):
    r = resolve_birth_timezone(*coords, d, t)
    assert r.status == "nonexistent"
    assert r.utc_offset_hours is None and r.offsets == ()


def test_unknown_birth_time_resolves_at_noon_and_says_so():
    r = resolve_birth_timezone(*TBILISI, date(1999, 5, 7), None)
    assert r.status == "ok" and r.utc_offset_hours == 5.0
    assert r.time_assumed is True


def test_unknown_time_on_a_clock_change_day_uses_noon_not_midnight():
    # The app computes at 12:00 when no birth time is given, so the offset must be the one in force at
    # noon: on 12 March 2023 New York is already on DST by noon (-4) but was on standard time at 01:00 (-5).
    spring = resolve_birth_timezone(*NEW_YORK, date(2023, 3, 12), None)
    assert (spring.status, spring.utc_offset_hours, spring.time_assumed) == ("ok", -4.0, True)
    assert resolve_birth_timezone(*NEW_YORK, date(2023, 3, 12), time(1, 0)).utc_offset_hours == -5.0
    # 5 Nov 2023: by noon DST has ended (-5), while 00:30 was still DST (-4).
    fall = resolve_birth_timezone(*NEW_YORK, date(2023, 11, 5), None)
    assert (fall.status, fall.utc_offset_hours) == ("ok", -5.0)
    assert resolve_birth_timezone(*NEW_YORK, date(2023, 11, 5), time(0, 30)).utc_offset_hours == -4.0


def test_zone_is_found_from_coordinates_including_across_a_us_zone_border():
    el_paso = resolve_birth_timezone(31.7619, -106.4850, date(2023, 7, 1), time(12, 0))
    houston = resolve_birth_timezone(29.7604, -95.3698, date(2023, 7, 1), time(12, 0))
    assert (el_paso.tz_name, el_paso.utc_offset_hours) == ("America/Denver", -6.0)
    assert (houston.tz_name, houston.utc_offset_hours) == ("America/Chicago", -5.0)


# --- the resolved value is what actually reaches the astronomical calculation ---------------------


def _iso(d: str, t: str, offset_hours: float) -> str:
    # Same construction the frontend uses: local wall clock + ISO offset suffix.
    sign = "-" if offset_hours < 0 else "+"
    total = round(abs(offset_hours) * 60)
    return f"{d}T{t}:00{sign}{total // 60:02d}:{total % 60:02d}"


def test_resolved_offset_becomes_the_exact_utc_instant_used_by_swiss_ephemeris():
    offset = resolve_birth_timezone(*TBILISI, date(1999, 5, 7), time(23, 30)).utc_offset_hours
    iso = _iso("1999-05-07", "23:30", offset)
    assert iso == "1999-05-07T23:30:00+05:00"
    # 23:30 local at UTC+5 is 18:30 UTC; independent Julian day via the library directly.
    assert to_julian_day(iso) == pytest.approx(swe.julday(1999, 5, 7, 18.5), abs=1e-9)
    # ...and NOT the instants produced by the old default or the "corrected" +4.
    assert to_julian_day(iso) != pytest.approx(to_julian_day("1999-05-07T23:30:00+00:00"), abs=1e-6)
    assert to_julian_day(iso) != pytest.approx(to_julian_day("1999-05-07T23:30:00+04:00"), abs=1e-6)


def test_chart_built_from_resolved_offset_equals_the_chart_for_the_same_utc_instant():
    lat, lon = TBILISI
    local = build_natal_chart(BirthData(datetime="1999-05-07T23:30:00+05:00", latitude=lat, longitude=lon))
    same_instant_utc = build_natal_chart(BirthData(datetime="1999-05-07T18:30:00+00:00", latitude=lat, longitude=lon))
    assert local.ascendant == pytest.approx(same_instant_utc.ascendant, abs=1e-9)
    assert [p.longitude for p in local.planets] == pytest.approx([p.longitude for p in same_instant_utc.planets])


def test_offset_materially_changes_the_ascendant_so_getting_it_wrong_is_visible():
    lat, lon = TBILISI
    asc = {
        off: build_natal_chart(BirthData(datetime=f"1999-05-07T23:30:00{off}", latitude=lat, longitude=lon)).ascendant
        for off in ("+00:00", "+04:00", "+05:00")
    }
    assert len({round(a, 3) for a in asc.values()}) == 3  # each offset yields a different Rising degree
    # One hour of offset error moves the Ascendant ~15 degrees: this is why +4 vs +5 matters.
    diff = (asc["+04:00"] - asc["+05:00"]) % 360
    assert 8 < diff < 25


# --- HTTP API ---------------------------------------------------------------------------------------

client = TestClient(app)


def _post(**body):
    return client.post("/api/timezone/resolve", json=body)


def test_api_returns_derived_zone_offset_and_label_for_the_tbilisi_case():
    r = _post(latitude=TBILISI[0], longitude=TBILISI[1], date="1999-05-07", time="23:30")
    assert r.status_code == 200
    body = r.json()
    assert body["status"] == "ok" and body["tz_name"] == "Asia/Tbilisi"
    assert body["utc_offset_hours"] == 5.0
    assert body["offsets"] == [{"utc_offset_hours": 5.0, "is_dst": True, "abbreviation": "+05", "label": "UTC+5"}]
    assert body["time_assumed"] is False


def test_api_labels_fractional_and_negative_offsets():
    kath = _post(latitude=KATHMANDU[0], longitude=KATHMANDU[1], date="2000-01-01", time="12:00").json()
    nyc = _post(latitude=NEW_YORK[0], longitude=NEW_YORK[1], date="2023-01-15", time="12:00").json()
    assert kath["offsets"][0]["label"] == "UTC+5:45"
    assert nyc["offsets"][0]["label"] == "UTC-5"


def test_api_reports_ambiguous_nonexistent_and_assumed_time_distinctly():
    amb = _post(latitude=NEW_YORK[0], longitude=NEW_YORK[1], date="2023-11-05", time="01:30").json()
    assert amb["status"] == "ambiguous" and amb["utc_offset_hours"] is None
    assert [o["label"] for o in amb["offsets"]] == ["UTC-4", "UTC-5"]
    gap = _post(latitude=NEW_YORK[0], longitude=NEW_YORK[1], date="2023-03-12", time="02:30").json()
    assert gap["status"] == "nonexistent" and gap["offsets"] == []
    noon = _post(latitude=TBILISI[0], longitude=TBILISI[1], date="1999-05-07").json()
    assert noon["status"] == "ok" and noon["time_assumed"] is True and noon["utc_offset_hours"] == 5.0


def test_api_rejects_bad_input_and_does_not_accept_birth_data_in_a_url():
    assert _post(latitude=91, longitude=0, date="2000-01-01").status_code == 422
    assert _post(latitude=0, longitude=181, date="2000-01-01").status_code == 422
    assert _post(latitude=0, longitude=0, date="not-a-date").status_code == 422
    # GET (query string) must not exist: birth date/place would land in access logs.
    assert client.get("/api/timezone/resolve?latitude=1&longitude=1&date=2000-01-01").status_code == 405
