export default function TermsPage() {
  return (
    <section className="screen active" id="terms">
      <div className="legal-page">
        <h1>Terms of Service</h1>
        <p className="updated">Last updated: [DATE — fill in when published]</p>

        <p>
          These Terms of Service (&quot;Terms&quot;) govern your use of Aureon (the
          &quot;Service&quot;), operated by [YOUR LEGAL ENTITY NAME / YOUR NAME] (&quot;Aureon&quot;,
          &quot;we&quot;, &quot;us&quot;). By creating an account or using the Service, you agree to
          these Terms. If you don&apos;t agree, don&apos;t use the Service.
        </p>

        <h2>1. What Aureon is — and isn&apos;t</h2>
        <p>
          Aureon generates astrology and numerology content — including a natal chart, numerology
          profile, and an AI chat companion — based on birth information you provide, for
          reflection and self-development purposes.
        </p>
        <p>
          <strong>
            Aureon is not a substitute for professional medical, psychological, legal, or financial
            advice.
          </strong>{" "}
          Nothing in the Service should be treated as a factual prediction about your life,
          health, relationships, or finances. If you&apos;re in crisis or experiencing a mental
          health emergency, please contact a licensed professional or local emergency services —
          not this app.
        </p>

        <h2>2. Eligibility</h2>
        <p>
          You must be at least 18 years old to create an account and use Aureon. By registering,
          you confirm that you meet this requirement.
        </p>

        <h2>3. Your account</h2>
        <p>
          You&apos;re responsible for keeping your login credentials secure and for all activity
          under your account. Tell us immediately if you suspect unauthorized access.
        </p>

        <h2>4. Subscriptions and billing</h2>
        <p>
          Aureon offers a free tier and paid subscription tiers (currently Premium, billed monthly).
          Paid subscriptions are processed by Paddle.com, our merchant of record — Paddle handles
          your payment details and billing; we never see or store your card information.
        </p>
        <ul>
          <li>Subscriptions renew automatically each billing period until cancelled.</li>
          <li>
            You can cancel anytime from your dashboard, which stops future renewals — cancellation
            does not retroactively refund the current billing period unless required by law.
          </li>
          <li>Prices may change; we&apos;ll give reasonable notice before any change takes effect for existing subscribers.</li>
        </ul>

        <h2>5. Acceptable use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service for anything unlawful, or to harass, abuse, or harm others</li>
          <li>Attempt to access another user&apos;s account or data</li>
          <li>Reverse-engineer, scrape, or interfere with the Service&apos;s normal operation</li>
          <li>Use the AI chat to generate content that violates applicable law</li>
        </ul>
        <p>We may suspend or terminate accounts that violate these Terms.</p>

        <h2>6. AI-generated content</h2>
        <p>
          Chat replies are generated by a third-party AI model based on your chart, numerology
          profile, and our reference material. AI output can be inaccurate, incomplete, or
          reflect patterns rather than facts — use your own judgment, especially for anything
          consequential.
        </p>

        <h2>7. Intellectual property</h2>
        <p>
          Aureon&apos;s software, design, reference content, and branding are owned by us or our
          licensors. You retain ownership of the personal information (birth details, chat
          messages) you provide, and grant us the right to process it solely to operate the
          Service for you.
        </p>

        <h2>8. Disclaimers and limitation of liability</h2>
        <p>
          The Service is provided &quot;as is&quot; without warranties of any kind. To the fullest
          extent permitted by law, we are not liable for indirect, incidental, or consequential
          damages arising from your use of the Service, including decisions made based on its
          content.
        </p>

        <h2>9. Changes to these Terms</h2>
        <p>
          We may update these Terms from time to time. Continued use of the Service after a change
          takes effect means you accept the updated Terms.
        </p>

        <h2>10. Termination</h2>
        <p>
          You may stop using the Service and delete your account at any time. We may suspend or
          terminate access for violations of these Terms.
        </p>

        <h2>11. Governing law</h2>
        <p>
          These Terms are governed by the laws of Georgia, without regard to conflict of law
          principles.
        </p>

        <h2>12. Contact</h2>
        <p>
          Questions about these Terms? Contact us at{" "}
          <a href="mailto:georgejermizashvili@gmail.com">georgejermizashvili@gmail.com</a>.
        </p>
      </div>
    </section>
  );
}
